create procedure [dbo].[Product_Create]
	@Name nvarchar (50),
	@Price decimal (28,10),
	@Manufacturer nvarchar(50),
	@ManufacturingYear int,
	@Depth decimal (28,10),
	@Width decimal (28,10),
	@Height decimal (28,10),
	@Weight decimal (28,10),
	@Wattage int,
	@Voltage int,
	@RemovableBasket nvarchar(30) = null,
	@EspressoType nvarchar(30) = null,
	@SteamNozzle nvarchar(30) = null,
	@IntegratedTimer nvarchar(30) = null,
	@BarsOfPressure nvarchar(30) = null,
	@DetachableBlades nvarchar(30) = null,
	@PivotingHead nvarchar(30) = null,
	@ProtectiveBumpers nvarchar(30) = null,
	@AppControlled nvarchar(30) = null,
	@RoomByRoomNavigation nvarchar(30) = null,
	@CombinationNozzle nvarchar(30) = null,
	@DustCupCapacity nvarchar(30) = null,
	@AdjustableSuction nvarchar(30) = null,
	@WetCleaning nvarchar(30) = null,
	@RetractableCord nvarchar(30) = null,
	@NonStickSoleplate nvarchar(30) = null,
	@AntiDripSystem nvarchar(30) = null,
	@SpeedSetting nvarchar(30) = null,
	@CoolShotButton nvarchar(30) = null,
	@RemovableEndCap nvarchar(30) = null,
	@DiffuserNozzle nvarchar(30) = null,
	@BleachDispenser nvarchar(30) = null,
	@Defrost nvarchar(30) = null,
	@Grill nvarchar(30) = null,
	@ThirdRack nvarchar(30) = null,
	@CupClips nvarchar(30) = null,
	@SilverwareBasket nvarchar(30) = null,
	@StemwareHolders nvarchar(30) = null,
	@UtensilSeparator nvarchar(30) = null,
	@VibrationReduction nvarchar(30) = null,
	@QuickWashCycle nvarchar(30) = null,
	@CylinderCapacity nvarchar(30) = null,
	@IceMaker nvarchar(30) = null,
	@TemperatureAlarm nvarchar(30) = null,
	@Freezer nvarchar(30) = null,
	@RemovableTeaInfuser nvarchar(30) = null,
	@WaterLevelWindow nvarchar(30) = null,
	@FullCircleConnectorOnThePowerbase nvarchar(30) = null,
	@TravelBag nvarchar(30) = null,
	@Programmable nvarchar(30) = null
as
begin
	declare 
	@PublicationTime datetime2 = SYSUTCDATETIME()
	insert into [dbo].[Product] (
		[Name],
		[Price],
		[Manufacturer],
		[ManufacturingYear],
		[Depth],
		[Width],
		[Height],
		[Weight],
		[Wattage],
		[Voltage],
	    [PublicationDate],
	    [LastUpdate],
		[RemovableBasket],
		[EspressoType],
		[SteamNozzle],
		[IntegratedTimer],
		[BarsOfPressure],
		[DetachableBlades],
		[PivotingHead],
		[ProtectiveBumpers],
		[AppControlled],
		[RoomByRoomNavigation],
		[CombinationNozzle],
		[DustCupCapacity],
		[AdjustableSuction],
		[WetCleaning],
		[RetractableCord],
		[NonStickSoleplate],
		[AntiDripSystem],
		[SpeedSetting],
		[CoolShotButton],
		[RemovableEndCap],
		[DiffuserNozzle],
		[BleachDispenser],
		[Defrost],
		[Grill],
		[ThirdRack],
		[CupClips],
		[SilverwareBasket],
		[StemwareHolders],
		[UtensilSeparator],
		[VibrationReduction],
		[QuickWashCycle],
		[CylinderCapacity],
		[IceMaker],
		[TemperatureAlarm],
		[Freezer],
		[RemovableTeaInfuser],
		[WaterLevelWindow],
		[FullCircleConnectorOnThePowerbase],
		[TravelBag],
		[Programmable]
		)
	values (
		@Name,
		@Price,
		@Manufacturer,
		@ManufacturingYear,
		@Depth,
		@Width,
		@Height,
		@Weight,
		@Wattage,
		@Voltage,
		@PublicationTime, @PublicationTime,
		@RemovableBasket,
		@EspressoType,
		@SteamNozzle,
		@IntegratedTimer,
		@BarsOfPressure,
		@DetachableBlades,
		@PivotingHead,
		@ProtectiveBumpers,
		@AppControlled,
		@RoomByRoomNavigation,
		@CombinationNozzle,
		@DustCupCapacity,
		@AdjustableSuction,
		@WetCleaning,
		@RetractableCord ,
		@NonStickSoleplate,
		@AntiDripSystem,
		@SpeedSetting,
		@CoolShotButton,
		@RemovableEndCap,
		@DiffuserNozzle,
		@BleachDispenser,
		@Defrost,
		@Grill,
		@ThirdRack,
		@CupClips,
		@SilverwareBasket,
		@StemwareHolders,
		@UtensilSeparator,
		@VibrationReduction,
		@QuickWashCycle,
		@CylinderCapacity,
		@IceMaker,
		@TemperatureAlarm,
		@Freezer,
		@RemovableTeaInfuser,
		@WaterLevelWindow,
		@FullCircleConnectorOnThePowerbase,
		@TravelBag,
		@Programmable
	)
	select scope_identity() as [ProductId]
end