create table [dbo].[Product] (
	[Id] bigint not null primary key identity (1,1),
	[Name] nvarchar (50) not null,
	[Price] decimal (28,10) not null,
	[Manufacturer] nvarchar(50) not null,
	[ManufacturingYear] int not null,
	[Depth] decimal (28,10) not null,
	[Width] decimal (28,10) not null,
	[Height] decimal (28,10) not null,
	[Weight] decimal (28,10) not null,
	[Wattage] int not null,
	[Voltage] int not null,
	[IsPublished] bit default 0 not null,
	[PublicationDate] datetime2 not null,
	[LastUpdate] datetime2 not null,
	[RemovableBasket] nvarchar(30),
	[EspressoType] nvarchar(30),
	[SteamNozzle] nvarchar(30),
	[IntegratedTimer] nvarchar(30),
	[BarsOfPressure] nvarchar(30),
	[DetachableBlades] nvarchar(30),
	[PivotingHead] nvarchar(30),
	[ProtectiveBumpers] nvarchar(30),
	[AppControlled] nvarchar(30),
	[RoomByRoomNavigation] nvarchar(30),
	[CombinationNozzle] nvarchar(30),
	[DustCupCapacity] nvarchar(30),
	[AdjustableSuction] nvarchar(30),
	[WetCleaning] nvarchar(30),
	[RetractableCord] nvarchar(30),
	[NonStickSoleplate] nvarchar(30),
	[AntiDripSystem] nvarchar(30),
	[SpeedSetting] nvarchar(30),
	[CoolShotButton] nvarchar(30),
	[RemovableEndCap] nvarchar(30),
	[DiffuserNozzle] nvarchar(30),
	[BleachDispenser] nvarchar(30),
	[Defrost] nvarchar(30),
	[Grill] nvarchar(30),
	[ThirdRack] nvarchar(30),
	[CupClips] nvarchar(30),
	[SilverwareBasket] nvarchar(30),
	[StemwareHolders] nvarchar(30),
	[UtensilSeparator] nvarchar(30),
	[VibrationReduction] nvarchar(30),
	[QuickWashCycle] nvarchar(30),
	[CylinderCapacity] nvarchar(30),
	[IceMaker] nvarchar(30),
	[TemperatureAlarm] nvarchar(30),
	[Freezer] nvarchar(30),
	[RemovableTeaInfuser] nvarchar(30),
	[WaterLevelWindow] nvarchar(30),
	[FullCircleConnectorOnThePowerbase] nvarchar(30),
	[TravelBag] nvarchar(30),
	[Programmable] nvarchar(30)
)
